version: '3.4'
services:
  dockerweb:
    env_file:
        - .env
    build:
      context: ./build/php
      dockerfile: Dockerfile
    container_name: dockerweb_php74
    depends_on:
      - mysqldb
    hostname: ${HOSTNAME}
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ${APP_SOURCE_DIRECTORY}:/var/www/html
    environment:
      MYSQL_HOST: ${HOSTNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: docker_db
    restart: always
 
  mysqldb:
    env_file:
        - .env
    build:
      context: ./build/mysql
      dockerfile: Dockerfile
    container_name: dockerweb_mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
    volumes:
      - ./build/data:/var/lib/mysql #mysql data directory | if you docker down or stop or rebuild, mysql data will remain 
    restart: always
    
  phpmyadmin:
    env_file:
        - .env
    image: phpmyadmin/phpmyadmin
    container_name: dockerweb_phpmyadmin
    depends_on:
      - mysqldb
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${HOSTNAME}
      PMA_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 64M
    restart: always

volumes:
  data:
